[package]
name = "rust-microservice-architecture"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["microservice"]

[dependencies]
microservice_1 = { path = "microservice/microservice_1" }
microservice_2 = { path = "microservice/microservice_2" }
